[package]
name = "rustingos"
version = "0.9.20-beta"
edition = "2024"
build = "src/build.rs"

[[bin]]
name = "rustingos"
path = "src/kernel.rs"
test = false

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
volatile = "0.2.6"
spin = "0.5.2"
string = "*"